config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :customers
  resources :posts do
    resources :comments
    #get '/comments', to: 'comments#index', as: 'comments'
    #post '/comments', to: 'comments#create'
    #get '/comments/new', to: 'comments#new', as: 'new_comments'
    #get '/comments/:id', to: 'comments#show', as: 'comment'
    #get '/comments/:id/edit', to: 'comments#edit', as: 'edit_comments'
    #patch '/comments/:id', to: 'comments#update'
    #delete '/comments/:id', to: 'comments#destroy'
  end

  resources :pages
#  get '/pages', to: 'pages#index'
#  post '/pages', to: 'pages#create'
#  get '/pages/new', to: 'pages#new', as: 'new_page'
#  get 'pages/:id', to: 'pages#show', as: 'page'
#  get '/pages/:id/edit', to: 'pages#edit', as: 'edit_page'
#  patch '/pages/:id', to: 'pages#update'
#  delete '/pages/:id', to: 'pages#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'customers#index'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  validates :product_name, presence: true
  validates :product_count, presence: true
  validates :product_count, numericality: { only_integer: true }
  validates_presence_of :customer
  def to_s
    costumer.full_name + "has ordered " + product_count.to_s + product_name
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit

  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
     if @order.save
       flash.notice = "The order record was created successfully."
       redirect_to @order
     else
       flash.now.alert = @order.errors.full_messages.to_sentence
       render :new
     end
    end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    if @order.update(order_params)
      flash.notice = "The order record was updated successfully."
      redirect_to @order
    else
      flash.now.alert = @order.errors.full_messages.to_sentence
      render :edit
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_path, notice: 'Order was successfully destroyed.'and return }
      format.json { head :no_content }
    end
  end
  private
    # Only allow a list of trusted parameters through.
      def order_params
        params.require(:order).permit(:product_name, :product_count, :customer_id)
      end
     def set_order
        @order = Order.find(params[:id])
     end
     def catch_not_found(e)
       Rails.logger.debug("We had a not found exception.")
       flash.alert = e.to_s
      redirect_to order_path
     end
   end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %>
    <%= f.text_field :product_name %>
  </div>

  <div class="field">
    <%= f.label :product_count %>
    <%= f.text_field :product_count %>
  </div>

  <div class="field">
    <%= f.label :customer %>
    <%= f.collection_select :customer_id, Customer.all, :id, :full_name, include_blank: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Product count</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.product_name %></td>
        <td><%= order.product_count %></td>
        <td><%= order.customer.full_name %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @order.product_name %>
</p>

<p>
  <strong>Product count:</strong>
  <%= @order.product_count %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer.full_name %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>