config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :customers
  resources :posts do
    resources :comments
    #get '/comments', to: 'comments#index', as: 'comments'
    #post '/comments', to: 'comments#create'
    #get '/comments/new', to: 'comments#new', as: 'new_comments'
    #get '/comments/:id', to: 'comments#show', as: 'comment'
    #get '/comments/:id/edit', to: 'comments#edit', as: 'edit_comments'
    #patch '/comments/:id', to: 'comments#update'
    #delete '/comments/:id', to: 'comments#destroy'
  end

  resources :pages
#  get '/pages', to: 'pages#index'
#  post '/pages', to: 'pages#create'
#  get '/pages/new', to: 'pages#new', as: 'new_page'
#  get 'pages/:id', to: 'pages#show', as: 'page'
#  get '/pages/:id/edit', to: 'pages#edit', as: 'edit_page'
#  patch '/pages/:id', to: 'pages#update'
#  delete '/pages/:id', to: 'pages#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'customers#index'
end

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
 <div class="field">
   <%= f.label :title %>
   <%= f.text_field :title %>
   </div>

 <div class="field">
   <%= f.label :body %>
   <%= f.text_area :body %>
   </div>

 <div class="field">
   <%= f.label :slug %>
   <%= f.text_field :slug %>
   </div>

   <div>
     <%= f.submit %>
     </div>
 <% end %>

app/views/pages/edit.html.erb
<%= render 'form', page: @page %>

app/views/pages/index.html.erb
<h1>Blog Pages</h1>
<% @pages.each do |page| %>
<p><%= link_to page.title, page %></p>
<% end %>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<%= render 'form', page: @page %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<p>
  <%= @page.body %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %>
<%= link_to 'Delete', @pages, method: :delete %>